### ISSUE TITLE
Not training but no error

### ISSUE THREAD

**Issue by DStickley** [cai199626/PDNet#3]
Hi, I have successfully preprocessed my data and when I run preprocess.py it generates data_merge_224x224x2_T.h5 but when trying to train I get:
Using TensorFlow backend.
channels_last
2019-01-10 14:49:54.773965: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
Then the process ends. I think that the cpu message can be ignored as I've had other models run successfully.

Either the model is not training or I'm doing something wrong when running test.py. You say to edit the test.py file but I'm not sure what needs editing here either. when I run test.py I get:
Using TensorFlow backend.
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    images = load()
  File "test.py", line 15, in load
    f = h5py.File('test_nlpr_224x224.h5','r')    
  File "/home/ds392/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ds392/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'test_nlpr_224x224.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by lalychen** [comment]
Is this problem solved? How do you need to change test.py?
